### ISSUE TITLE
Question  Cannot generate interfaces with your tool.I am doing something wrong

### ISSUE THREAD

**Issue by TedMobile** [rdavisau/essential-interfaces#1]
Hi
just a question not an issue,
I have downloaded your code to generate the inter
faces and whatever I put in the argument it gives an error

1)Downloaded your code from github
2)updated nuget for xamarinessentials to 0.8 preview
3)properties-debug of essentials-interfaces-generator - in the
  application arguments I put 2 arguments the path to xamarinessentials and the one
  where I want the output.
  
  
  I am definetely doing something wrong as I keep getting an error.
  
  Could you tell me what parameters you put in the application argument?
  
  sample code?
  thanks a lot for this tool

**Comment by rdavisau** [comment]
Hi -

No problems, the tool itself is not exactly documented - and rightly or wrongly (probably the latter) it's optimised for the build process rather than an end user. 

The tool is expecting two parameters: 

* path to Xamarin.Essentials _source_ (which is a submodule of this repo) 
* path to the nuget package output project folder (https://github.com/rdavisau/essential-interfaces/tree/master/src/output/Essential.Interfaces)

The tool reads from the source at the Xamarin.Essentials path, generates a model of the Essentials Api, then updates the output project accordingly (writes the Essentials.cs file and updates the csproj to include version information like the source commit). On the build server I then build the output project to make the NuGet package, but if you just want the output you can take the file at src/output/Essential.Interfaces/Essentials.cs after running the tool. 

So to do it by hand, from the console: 
#### Clone repo including submodules
`git clone --recurse-submodules https://github.com/rdavisau/essential-interfaces`
`cd essential-interfaces`

#### Move Xamarin.Essentials source to the desired commit
`cd submodule\Essentials`
`git checkout 26c14c7` (26c14c7 is the [latest release](https://github.com/xamarin/Essentials/releases/tag/0.8.0-preview))

#### Generate the interfaces
`cd ..\..\`  (back to the root of the repo)
`dotnet run -c Release --project src\essential-interfaces-generator\essential-interfaces-generator.csproj -- submodule\Essentials src\output\Essential.Interfaces`

Now src/output/Essential.Interfaces/Essentials.cs has your interfaces. 

So that's how you can do it by hand, but if you just want the outputs there is a NuGet package on MyGet (waiting for once release cycle of Xamarin.Essentials to make sure it all works ok before moving to NuGet), and the raw source outputs are published to [this bucket](https://rdavisau.blob.core.windows.net/essential-interfaces?restype=container&comp=list) - for example, the output for 26c14c7 in the example above is [here](https://rdavisau.blob.core.windows.net/essential-interfaces/essentials-0.8.0-preview-0-g26c14c7.cs).

Hope that helps!

**Comment by TedMobile** [comment]
BRILLIANT .thanks  for your excellent reply.Apologies for late reply!!!! Noticed that another version has come out too.

**Comment by rdavisau** [comment]
😃 

These days you can get the outputs from https://essential-interfaces.azurewebsites.net too.
